### ISSUE TITLE
gui making questions

### ISSUE THREAD

**Issue by gabieab** [pct-code/scalewiz#37]
hello,

im an undergrad student (non-CS major with very limited coding/GitHub experience) working on a live data-logging/data monitoring gui/application and have stumbled upon your project. i currently have a working gui, but the code is extremely unoptimized and as a result I'm having a bit of trouble documenting it. i just wanted to reach out and ask if i could contact you to ask a couple (potentially a lot lol) of questions?

in general though, i was wondering how/why you built the overall code structure the way you did? for ex. what does `class ScaleWiz(ttk.Frame)` do exactly (I have `class ClassName(ttk.Tk)` in my code instead; do you happen to know what the difference is and why `Frame` might be better)? 

any help or resources you used at all would be extremely helpful, and thanks for making this amazing project available!

**Comment by teauxfu** [comment]
Hey there, thanks for checking out my project! I also am a non-CS major, and I'm happy to answer any questions you may have.

How:
The code is structured into "models" which are non-UI classes that handle holding data and operating on it.
Then there are "components" which are UI classes (inheriting from tk.Frame or similar as you noticed) bundled with a minimum of business logic so that they can interact with the models. Lastly I have a few "helpers" which are supposed to just be functions that can be run without needing to be on a particular object/class etc. -- the goal was that these can be run from anywhere.

Why:
The code structure kind of formed organically as I learned, so not everything here is an example of "best practices." I initially aimed to write everything according to a design pattern called model view controller (MVC). The idea there is the model is the brains/data structure, the view is the UI layer presented to the user, and the controller is the plumbing that lets them talk to each other when the user interacts with the program. The idea is that the model and view should be independent, allowing one to easily swap out one view of a model for another. This is kind of related to the idea of separation of concerns.

There was not an apparent/easy way to do that due to the nature of how Tkinter is used within Python. Because the project is relatively small in scope and I'm the only dev working on it I felt comfortable departing from a rigid design pattern. Instead, I tried to bundle together a minimum of UI code and logic into "components," borrowing the term from React. Although the components in ScaleWiz are actually built quite differently from React components, they are used in somewhat analogous ways.
My model/component/helper scheme is basically an adaptation of model/view/controller that is a little more intuitive (for me) for using with Tkinter.

As for the `ScaleWiz` inheriting from `Frame` -- it was just a choice. I like using `Frame` as a base for components because it gives you access to helpful Tkinter methods without imposing any UI elements on you. You may notice I plug the `ScaleWiz` Frame into a `Tk` instance here, even though `ScaleWiz` itself has no UI elements (although it's children "components" do).

https://github.com/pct-code/scalewiz/blob/e200d07ebb3dcc22571db823c5c77af0394255a0/scalewiz/__main__.py#L1-L18

However, if I remember correctly, Tkinter will spawn a root `Tk` object for itself if you don't do it explicitly. 
The advantage to doing it explicitly is that you can hold on to a reference to that root object in case you need to use it later.
